/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/ipad.gltf -t -r public 
Author: 253672745 (https://sketchfab.com/i.lim253672745)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ipad-pro-m4-2024-with-apple-pencil-pro-and-mkb-1a76ebc17fdf4abd85fa3a12686b0e67
Title: iPad Pro M4 2024 with Apple Pencil Pro and MKB
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { AnimationClip } from 'three'

type GLTFResult = GLTF & {
  nodes: {
    ZbqqbBlsPnIdnwL: THREE.Mesh
    QunvAdFwDCgNQnS: THREE.Mesh
    rkQskEUXrwIOnam: THREE.Mesh
    NzckuxOUVtJxvYl: THREE.Mesh
    bBZGCIXdAwFSogJ: THREE.Mesh
    JhJRxeuwtfjkRXU: THREE.Mesh
    YXSrIUEUoDEmjeJ: THREE.Mesh
    mxfEKUsoPrcXOKy: THREE.Mesh
    eFENyJZbvWZPrHl: THREE.Mesh
    EGLEFVSTipbvlCA: THREE.Mesh
    mhoxbXtnJWvTVtX: THREE.Mesh
    PgzvTgQuXyFpnoM: THREE.Mesh
    kvRozmfuInNsUMg: THREE.Mesh
    WElrhCMnAdeuHDI: THREE.Mesh
    UTSFNcOcyCyXYhQ: THREE.Mesh
    GetlFNcPJRCGpIS: THREE.Mesh
    jxEBNmeQPdSqNgB: THREE.Mesh
    sgrcsOILDCZaCHz: THREE.Mesh
    TeADrCIkPSJFbpR: THREE.Mesh
    ELsWOpEbZOoVxhz: THREE.Mesh
    CjrRffKTkbXlADv: THREE.Mesh
    gcqbNmuCfTFWbSj: THREE.Mesh
    GsEryEAIeOiIKDF: THREE.Mesh
    TwIIGThZUuRqrov: THREE.Mesh
    DsmqZcretvvKQrK: THREE.Mesh
    tjgkvbgCMtUknTN: THREE.Mesh
    YRyxzVdrHIgAdHS: THREE.Mesh
    DusXbgQdScmNkTY: THREE.Mesh
    OCglbEZclAkwtRa: THREE.Mesh
    EnPXeynPHvcnTTM: THREE.Mesh
    QVOnmCxyGMlyRHQ: THREE.Mesh
    xviDZsHJMmtDfne: THREE.Mesh
    IpOuDnYMUgcohpj: THREE.Mesh
    cAIlWSHSYIjcXUz: THREE.Mesh
    UTQGssgocJTvGje: THREE.Mesh
    oeFmvUVnxhLmLhN: THREE.Mesh
    BglrNkUFMbMRzrJ: THREE.Mesh
    fpqPxeOPBCrhuRI: THREE.Mesh
    jFrPeGgKbZHAWPl: THREE.Mesh
    sOTRqdWUJrmMcvh: THREE.Mesh
    PJEfKGdaocLJXTm: THREE.Mesh
    lCYrwSMIohDdVEw: THREE.Mesh
    fyRDOddTGUtoLdL: THREE.Mesh
    oLTsrTCRfCKidAq: THREE.Mesh
    OKkSZQiCujRVyGQ: THREE.Mesh
    HHajbdbOkgPZaDc: THREE.Mesh
  }
  materials: {
    lSJYgIXjRPNZZfu: THREE.MeshStandardMaterial
    RDNWQpbOmsATJyy: THREE.MeshStandardMaterial
    DbWEVTPEJRihIps: THREE.MeshStandardMaterial
    QZITrmzGwovtLMP: THREE.MeshStandardMaterial
    klRtNKKtYoJyQjE: THREE.MeshStandardMaterial
    aKccFvRWJKlelEY_0: THREE.MeshStandardMaterial
    NovRtfFHsnBTSRQ: THREE.MeshStandardMaterial
    kzFbNGvAxIUbjaN: THREE.MeshStandardMaterial
    QVUQTCiIDodQaat: THREE.MeshStandardMaterial
    oLHDvIuvJkYWzhP: THREE.MeshStandardMaterial
    NgWiKdyzrMHFKgO: THREE.MeshStandardMaterial
    jimweAFKrptXGYl: THREE.MeshStandardMaterial
    qsTxLrQrTgIOzFy: THREE.MeshStandardMaterial
    scdiHbbqKMrxLvG: THREE.MeshStandardMaterial
    InnfZKFnIvizAUj: THREE.MeshStandardMaterial
    SigyjnNsSKuPyMi: THREE.MeshStandardMaterial
    FeUinFqscIjbiVr: THREE.MeshStandardMaterial
    VorBKiydaDJLVHL: THREE.MeshStandardMaterial
    jcIAFNBmpIebNBE: THREE.MeshStandardMaterial
    NpsCAeRehOuFXTY: THREE.MeshStandardMaterial
    zZPaOeLokulMLqy: THREE.MeshStandardMaterial
    fyoZKPFMmPovULG: THREE.MeshStandardMaterial
    oiHwNGqsyJJtsEl: THREE.MeshStandardMaterial
    ysdjePmMeEWgWAI: THREE.MeshStandardMaterial
    ZSdXlUrdFIyABlP: THREE.MeshStandardMaterial
    DENhhPEhWALeqBz: THREE.MeshStandardMaterial
    IDEBjyIFlCgKhYh: THREE.MeshStandardMaterial
    cmmYgpYmwLPZoWA: THREE.MeshStandardMaterial
    YYtHDfZOscDlfKc: THREE.MeshStandardMaterial
    cuQUVFSKUPupHoi: THREE.MeshStandardMaterial
    zQlxjGiQQymkYFj: THREE.MeshStandardMaterial
    aKccFvRWJKlelEY: THREE.MeshStandardMaterial
    MKsrtFZIAzUGPEp: THREE.MeshStandardMaterial
    dpZySlRztLPxZkW: THREE.MeshStandardMaterial
    qabwpJDEVsahugG: THREE.MeshStandardMaterial
    rhMDRtMKXUCgCbg: THREE.MeshStandardMaterial
    QfozzJBTjsdzTcS: THREE.MeshStandardMaterial
    VwFiedHiVFXDQBu: THREE.MeshStandardMaterial
  }
  animations: AnimationClip[] 
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/ipad.gltf') as GLTFResult
  return (
    <group {...props} dispose={null} rotation={[6.5, 11, 5.5]} position={[0, -1.5, 0]}>
      <group scale={0.13}>
        <group position={[0, 0, -0.744]}>
          <mesh geometry={nodes.ZbqqbBlsPnIdnwL.geometry} material={materials.lSJYgIXjRPNZZfu} />
          <mesh geometry={nodes.QunvAdFwDCgNQnS.geometry} material={materials.RDNWQpbOmsATJyy} />
          <mesh geometry={nodes.rkQskEUXrwIOnam.geometry} material={materials.DbWEVTPEJRihIps} />
          <mesh geometry={nodes.NzckuxOUVtJxvYl.geometry} material={materials.QZITrmzGwovtLMP} />
        </group>
        <mesh geometry={nodes.kvRozmfuInNsUMg.geometry} material={materials.oLHDvIuvJkYWzhP} />
        <mesh geometry={nodes.mxfEKUsoPrcXOKy.geometry} material={materials.aKccFvRWJKlelEY_0} />
        <mesh geometry={nodes.eFENyJZbvWZPrHl.geometry} material={materials.kzFbNGvAxIUbjaN} />
        <mesh geometry={nodes.bBZGCIXdAwFSogJ.geometry} material={materials.klRtNKKtYoJyQjE} />
        <mesh geometry={nodes.JhJRxeuwtfjkRXU.geometry} material={materials.aKccFvRWJKlelEY_0} />
        <mesh geometry={nodes.YXSrIUEUoDEmjeJ.geometry} material={materials.NovRtfFHsnBTSRQ} />
        <mesh geometry={nodes.EGLEFVSTipbvlCA.geometry} material={materials.QVUQTCiIDodQaat} />
        <mesh geometry={nodes.mhoxbXtnJWvTVtX.geometry} material={materials.oLHDvIuvJkYWzhP} />
        <mesh geometry={nodes.PgzvTgQuXyFpnoM.geometry} material={materials.NgWiKdyzrMHFKgO} />
        <mesh geometry={nodes.UTSFNcOcyCyXYhQ.geometry} material={materials.qsTxLrQrTgIOzFy} />
        <mesh geometry={nodes.GetlFNcPJRCGpIS.geometry} material={materials.oLHDvIuvJkYWzhP} />
        <mesh geometry={nodes.jxEBNmeQPdSqNgB.geometry} material={materials.scdiHbbqKMrxLvG} />
        <mesh geometry={nodes.sgrcsOILDCZaCHz.geometry} material={materials.kzFbNGvAxIUbjaN} />
        <mesh geometry={nodes.TeADrCIkPSJFbpR.geometry} material={materials.InnfZKFnIvizAUj} />
        <mesh geometry={nodes.ELsWOpEbZOoVxhz.geometry} material={materials.InnfZKFnIvizAUj} />
        <mesh geometry={nodes.CjrRffKTkbXlADv.geometry} material={materials.InnfZKFnIvizAUj} />
        <mesh geometry={nodes.gcqbNmuCfTFWbSj.geometry} material={materials.SigyjnNsSKuPyMi} />
        <mesh geometry={nodes.GsEryEAIeOiIKDF.geometry} material={materials.SigyjnNsSKuPyMi} />
        <mesh geometry={nodes.TwIIGThZUuRqrov.geometry} material={materials.aKccFvRWJKlelEY_0} />
        <mesh geometry={nodes.WElrhCMnAdeuHDI.geometry} material={materials.jimweAFKrptXGYl} />
        <mesh geometry={nodes.DsmqZcretvvKQrK.geometry} material={materials.FeUinFqscIjbiVr} />
        <mesh geometry={nodes.tjgkvbgCMtUknTN.geometry} material={materials.VorBKiydaDJLVHL} />
        <mesh geometry={nodes.YRyxzVdrHIgAdHS.geometry} material={materials.jcIAFNBmpIebNBE} />
        <mesh geometry={nodes.DusXbgQdScmNkTY.geometry} material={materials.NpsCAeRehOuFXTY} />
        <mesh geometry={nodes.OCglbEZclAkwtRa.geometry} material={materials.zZPaOeLokulMLqy} />
        <mesh geometry={nodes.EnPXeynPHvcnTTM.geometry} material={materials.fyoZKPFMmPovULG} />
        <mesh geometry={nodes.QVOnmCxyGMlyRHQ.geometry} material={materials.oiHwNGqsyJJtsEl} />
        <mesh geometry={nodes.xviDZsHJMmtDfne.geometry} material={materials.ysdjePmMeEWgWAI} />
        <mesh geometry={nodes.IpOuDnYMUgcohpj.geometry} material={materials.ZSdXlUrdFIyABlP} />
        <mesh geometry={nodes.cAIlWSHSYIjcXUz.geometry} material={materials.DENhhPEhWALeqBz} />
        <mesh geometry={nodes.UTQGssgocJTvGje.geometry} material={materials.IDEBjyIFlCgKhYh} />
        <mesh geometry={nodes.oeFmvUVnxhLmLhN.geometry} material={materials.cmmYgpYmwLPZoWA} />
        <mesh geometry={nodes.BglrNkUFMbMRzrJ.geometry} material={materials.YYtHDfZOscDlfKc} />
        <mesh geometry={nodes.fpqPxeOPBCrhuRI.geometry} material={materials.cuQUVFSKUPupHoi} />
        <mesh geometry={nodes.jFrPeGgKbZHAWPl.geometry} material={materials.zQlxjGiQQymkYFj} />
        <mesh geometry={nodes.sOTRqdWUJrmMcvh.geometry} material={materials.aKccFvRWJKlelEY} />
        <mesh geometry={nodes.PJEfKGdaocLJXTm.geometry} material={materials.MKsrtFZIAzUGPEp} />
        <mesh geometry={nodes.lCYrwSMIohDdVEw.geometry} material={materials.dpZySlRztLPxZkW} />
        <mesh geometry={nodes.fyRDOddTGUtoLdL.geometry} material={materials.qabwpJDEVsahugG} />
        <mesh geometry={nodes.oLTsrTCRfCKidAq.geometry} material={materials.rhMDRtMKXUCgCbg} />
        <mesh geometry={nodes.OKkSZQiCujRVyGQ.geometry} material={materials.QfozzJBTjsdzTcS} />
        <mesh geometry={nodes.HHajbdbOkgPZaDc.geometry} material={materials.VwFiedHiVFXDQBu} />
      </group>
    </group>
  )
}

useGLTF.preload('/ipad.gltf')
